# Generated by Django 4.0.6 on 2022-08-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=200, unique_for_month='date'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='description',
            field=models.CharField(max_length=200, unique_for_month='date'),
        ),
    ]
