# Generated by Django 4.0.6 on 2022-08-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Health', 'Health'), ('Home', 'Home'), ('Transport', 'Transport'), ('School', 'School'), ('Fun', 'Fun'), ('Unexpected', 'Unexpected'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
